### ISSUE TITLE
Dot is misplaced

### ISSUE THREAD

**Issue by WJRovers** [Tools4everBV/HelloID-Conn-Prov-Target-KPN-Bart#1]
The enable PS script has a trailing dot that should've been placed within the string statement.
In current state the else-case would cause errors.

https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-KPN-Bart/blob/665b33a1cde3f65c6eacc3f149465a12f96f2bc1/enable.ps1#L174C12-L174C12

**Comment by Rick-Jongbloed** [comment]
Can be closed when we release the PsV2 version of the connector.

**Comment by Rick-Jongbloed** [comment]
Fixed
